import { Lead } from "./types";

export const initialLeads: Lead[] = [
    {
        id: "1",
        company: "TechCorp Solutions",
        status: "new",
        priority: "high priority",
        industry: "Technology",
        employees: "50-200 employees",
        location: "United Kingdom",
        contactName: "Sarah Johnson",
        contactEmail: "sarah.johnson@techcorp.com",
        contactPhone: "+44 20 1234 5678",
        accentColor: "bg-green-500",
        notes: "",
    },
    {
        id: "2",
        company: "FinanceHub Ltd",
        status: "contacted",
        priority: "high priority",
        industry: "Finance",
        employees: "200-500 employees",
        location: "United Kingdom",
        contactName: "Alex Mercer",
        contactEmail: "alex.mercer@financehub.com",
        contactPhone: "+44 20 2345 6789",
        accentColor: "bg-green-500",
        notes: "",
    },
    {
        id: "3",
        company: "HealthPlus Medical",
        status: "meeting booked",
        priority: "medium priority",
        industry: "Healthcare",
        employees: "100-200 employees",
        location: "United Kingdom",
        contactName: "Emma Watson",
        contactEmail: "emma.watson@healthplus.com",
        contactPhone: "+44 20 3456 7890",
        accentColor: "bg-yellow-500",
        notes: "",
    },
];
