import { PlacementItem } from "./types";

export const placementsData: PlacementItem[] = [
    {
        id: "1",
        candidateId: "1",
        candidateName: "Alex Thompson",
        candidateEmail: "alex.thompson@email.com",
        position: "Senior Software Engineer",
        client: "GlobalTech Industries",
        salary: "£85,000",
        fee: "£17,000",
        placedDate: "15/04/2026",
        status: "Started",
    },
    {
        id: "2",
        candidateId: "2",
        candidateName: "Sarah Martinez",
        candidateEmail: "sarah.martinez@email.com",
        position: "Product Manager",
        client: "GlobalTech Industries",
        salary: "£65,000",
        fee: "£13,000",
        placedDate: "20/03/2026",
        status: "Guarantee Period",
    },
    {
        id: "3",
        candidateId: "3",
        candidateName: "James Wilson",
        candidateEmail: "james.wilson@email.com",
        position: "Store Manager",
        client: "RetailPro Group",
        salary: "£42,000",
        fee: "£8,400",
        placedDate: "01/05/2026",
        status: "Offer Accepted",
    },
    {
        id: "4",
        candidateId: "4",
        candidateName: "Emma Davis",
        candidateEmail: "emma.davis@email.com",
        position: "Operations Manager",
        client: "Manufacturing United",
        salary: "£58,000",
        fee: "£11,600",
        placedDate: "10/05/2026",
        status: "Offer Sent",
    },
    {
        id: "5",
        candidateId: "1",
        candidateName: "Alex Thompson",
        candidateEmail: "alex.thompson@email.com",
        position: "Senior Software Engineer",
        client: "GlobalTech Industries",
        salary: "£75,000",
        fee: "£15,000",
        placedDate: "10/02/2026",
        status: "Started",
    },
    {
        id: "6",
        candidateId: "2",
        candidateName: "Sarah Martinez",
        candidateEmail: "sarah.martinez@email.com",
        position: "Product Manager",
        client: "GlobalTech Industries",
        salary: "£68,000",
        fee: "£13,600",
        placedDate: "15/01/2026",
        status: "Guarantee Period",
    },
    {
        id: "7",
        candidateId: "3",
        candidateName: "James Wilson",
        candidateEmail: "james.wilson@email.com",
        position: "Store Manager",
        client: "RetailPro Group",
        salary: "£38,000",
        fee: "£7,600",
        placedDate: "20/04/2026",
        status: "Started",
    },
    {
        id: "8",
        candidateId: "4",
        candidateName: "Emma Davis",
        candidateEmail: "emma.davis@email.com",
        position: "Operations Manager",
        client: "Manufacturing United",
        salary: "£52,000",
        fee: "£10,400",
        placedDate: "25/05/2026",
        status: "Offer Accepted",
    },
];
